name: ci

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'yarn'

    - name: Build Releases
      if: startsWith(github.ref, 'refs/tags/')
      run: ./scripts/build-tar.sh

    - name: Upload Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: file.tar.xz
        draft: true
        prerelease: true

